# Generated by Django 3.2.3 on 2021-06-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20210613_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='extra_note',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
